config/routes.rb
HexGame::Application.routes.draw do
  get "dev/qunit"

  get 'sessions/create'
  get 'sessions/new'

  post '/games/end_turn' => 'games#end_turn'
  get '/games/get_turn' => 'games#get_turn'
  get '/games/is_it_my_turn' => 'games#is_it_my_turn'
  post '/messages/:id/mark_read' => 'messages#mark_read'

  resources :games
  resources :maps
  resources :messages
  resources :players
  resources :tile_types
  resources :unit_types

  
  match "/auth/:provider/callback" => "sessions#create" 
  match "/auth/failure" => "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout 

  root :to => "games#index"

end

app/models/map.rb
class Map < ActiveRecord::Base
  serialize :tile_data
  serialize :unit_data
  has_many :games, :dependent => :destroy
  validates :name, :presence => true, :length => {:minimum => 4}
  validates :height, :presence=>true, :numericality => {:greater_than_or_equal_to => 2}
  validates :width, :presence=>true, :numericality => {:greater_than_or_equal_to => 2}
  validates :number_of_players, :presence=>true, :numericality=>{:greater_than_or_equal_to=>2, :less_than_or_equal_to=>4}
  validates :unit_data, :length => {:minimum => 1, :message => 'You must have units on the map! (otherwise it will be a rather boring game)'}
end




# == Schema Information
#
# Table name: maps
#
#  id                :integer         not null, primary key
#  name              :string(255)
#  tile_data         :text
#  created_at        :datetime
#  updated_at        :datetime
#  height            :integer
#  width             :integer
#  unit_data         :text
#  number_of_players :integer         default(2), not null
#

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  skip_filter :check_authentication
  before_filter :check_authentication, :except => [:show]
  skip_filter :check_admin
  before_filter :check_admin, :except=>:show
  
  caches_page :show, :if => Proc.new { |c| c.request.format.json? }
  
  #
  # GET /maps
  #
  def index
    @maps = Map.find(:all)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  #
  # GET /maps/1
  #
  def show
    @map = Map.find(params[:id])

    respond_to do |format|
      format.html   { check_authentication } # show.html.erb
      #format.json { render :json => @map } # odd deprecated warnign
      format.json { render :text => @map.to_json }
      format.yaml { render :text => @map.to_yaml }
    end
  end

  #
  # GET /maps/new
  #
  def new
    @map = Map.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  #
  # GET /maps/1/edit
  #
  def edit
    @map = Map.find(params[:id])
  end

  #
  # POST /maps
  #
  def create
    save(params)
  end

  #
  # PUT /maps/1
  #
  def update
    save(params)
  end

  #
  # DELETE /maps/1
  #
  def destroy
    @map = Map.find(params[:id])
    @map.destroy
    
    expire_page :action=>'show', :id=>params[:id], :format=>'json'

    respond_to do |format|
      format.html { redirect_to(maps_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  #
  # Saves map, both new and existing
  #
  def save(params)
    @map = params[:id] ? Map.find(params[:id]) : Map.new(params[:map])
    
    if params[:id]
      expire_page :action=>'show', :id=>params[:id], :format=>'json'
    end

    respond_to do |format|
      if @map.update_attributes(params[:map])
        format.json { render :json => @map }
      else
        format.json  { render :json => @map.errors }
      end
    end
  end

end

app/helpers/maps_helper.rb
module MapsHelper
  def load_js_map(map, variable_name)
    #return if map.nil?
  	out =  "#{variable_name} = new Hexwar.Map(#{map.height}, #{map.width}, '#{map.name}', #{map.id});
          	var row = null;"

  	map.tile_data.each do |key, row|
  		out += "row = [];"
  		row.each do |col_key, col|
  			out += "row[#{col_key}] = tile_types[#{col[:type_index]}].createTile();"
  		end
  	out += "#{variable_name}.tile_data.data[#{key}] = row;"
  	end
  	
  	out
  end

  def load_js_map_units(map, variable_name)
    #return if map.nil?
  	out =  "#{variable_name}.unit_data = [];"
  	
    map.unit_data.each do |key, unit|
      out += "#{variable_name}.unit_data[#{key}] = unit_types[#{unit[:type_index]}].createUnit('#{unit[:team]}', #{unit[:x]}, #{unit[:y]});"
    end
    
    out
  end
end

app/views/maps/_form.html.erb
<script type="text/javascript">
$(function(){
	var tile_factory = Hexwar.ServiceContainer.get('TileFactory');
	tile_types = tile_factory.tile_types;
	var unit_factory = Hexwar.ServiceContainer.get('UnitFactory');
	unit_types = unit_factory.unit_types;
	var maped = new Hexwar.MapEditor(map);
});
</script>
<h1>Map Editor</h1>
<%= link_to 'Back to List', maps_path %><br /><br />
<button id="btn_save" >Save</button>
<button id="btn_undo">Undo</button>
<button id="btn_toolbox">Toolbox</button>
<%= form_for(@map) do |f| %>
	<p>Name: <%= f.text_field :name %></p>
	<p># of Players <%= f.select :number_of_players, (2..4).to_a %></p>
<% end %>
<div id="hexmap01" class="hexmap">
</div>
<div id="toolbox" title="Toolbox" class="dialog"></div>

app/views/maps/edit.html.erb
<script type="text/javascript">
	$(function() {
		var tile_factory = Hexwar.ServiceContainer.get('TileFactory');
		tile_types = tile_factory.tile_types;
		var unit_factory = Hexwar.ServiceContainer.get('UnitFactory');
		unit_types = unit_factory.unit_types;
	
		map = new Hexwar.Map();
		map.loadFromServer(<%=@map.id%>);
	});

</script>

<%= render 'form' %>


<%= render 'layouts/preload' %>

app/views/maps/index.html.erb
<h1>Listing maps</h1>
<%= link_to 'New Map', new_map_path, :class=>:button %>
<table class="model_index">
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

<% @maps.each do |map| %>
  <tr>
    <td><%= map.name %></td>
		<td><%= link_to 'Show', map, :class=>:button %> <%= link_to 'Edit', edit_map_path(map), :class=>:button %> <%= link_to 'Destroy', map, :confirm => 'Are you sure?', :method => :delete, :class=>:button %></td>
  </tr>
<% end %>
</table>

app/views/maps/new.html.erb
<script type="text/javascript">
	var map = null;
</script>

<%= render 'form' %>


<%= render 'layouts/preload' %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_map_path(@map), :class=>'button' %>

<p>
  <b>Name:</b>
  <%= @map.name %>
</p>
<p>
  <b># of Players:</b>
  <%= @map.number_of_players %>
</p>

<p>
  <b>Data:</b>
	<div id="hexmap01" class="hexmap"></div>

	<script type="text/javascript">
	$(function() {
		var map = new Hexwar.Map();
		map.loadFromServer(<%=@map.id%>);
		
		var mapview = new Hexwar.MapView($('#hexmap01'));
		mapview.drawMap(map);
	});
	</script>
</p>


<%= render 'layouts/preload' %>