config/routes.rb
HexGame::Application.routes.draw do
  get "dev/qunit"

  get 'sessions/create'
  get 'sessions/new'

  post '/games/end_turn' => 'games#end_turn'
  get '/games/get_turn' => 'games#get_turn'
  get '/games/is_it_my_turn' => 'games#is_it_my_turn'
  post '/messages/:id/mark_read' => 'messages#mark_read'

  resources :games
  resources :maps
  resources :messages
  resources :players
  resources :tile_types
  resources :unit_types

  
  match "/auth/:provider/callback" => "sessions#create" 
  match "/auth/failure" => "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout 

  root :to => "games#index"

end

app/controllers/tile_types_controller.rb
class TileTypesController < ApplicationController
  skip_filter :check_authentication
  before_filter :check_authentication, :except => [:index]
  skip_filter :check_admin
  before_filter :check_admin, :except=>:index
  
  caches_page :index, :if => Proc.new { |c| c.request.format.json? }
  
  # GET /tile_types
  # GET /tile_types.xml
  def index
    @tile_types = TileType.find(:all, :order=>:position)

    respond_to do |format|
      format.html { check_authentication } # index.html.erb
      format.json { render :json => @tile_types }
      format.xml  { render :xml => @tile_types }
    end
  end

  # GET /tile_types/1
  # GET /tile_types/1.xml
  def show
    @tile_type = TileType.find(params[:id])
    @unit_types = UnitType.find(:all, :order=>:position)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tile_type }
    end
  end

  # GET /tile_types/new
  # GET /tile_types/new.xml
  def new
    @tile_type = TileType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tile_type }
    end
  end

  # GET /tile_types/1/edit
  def edit
    @tile_type = TileType.find(params[:id])
    @unit_types = UnitType.find(:all, :order=>:position)
  end

  # POST /tile_types
  # POST /tile_types.xml
  def create
    @tile_type = TileType.new(params[:tile_type])
    
    expire_page :action=>'index', :format=>'json'

    respond_to do |format|
      if @tile_type.save
        format.html { redirect_to(tile_types_url, :notice => 'Tile type was successfully created.') }
        format.xml  { render :xml => @tile_type, :status => :created, :location => @tile_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tile_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  #
  # PUT /tile_types/1
  #
  def update
    @tile_type = TileType.find(params[:id])
    
    expire_page :action=>'index', :format=>'json'

    respond_to do |format|
      if @tile_type.update_attributes(params[:tile_type])
        format.html { redirect_to(tile_types_url, :notice => 'Tile type was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /tile_types/1
  # DELETE /tile_types/1.xml
  def destroy
    @tile_type = TileType.find(params[:id])
    @tile_type.destroy
    
    expire_page :action=>'index', :format=>'json'

    respond_to do |format|
      format.html { redirect_to(tile_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tile_types_helper.rb
module TileTypesHelper
  def display_tile_img(tile_type)
    "<div style=\"background: url(#{tile_type.img}) no-repeat scroll #{tile_type.img_x}px #{tile_type.img_y*-1}px transparent; width:72px; height:72px;\"></div>"
  end
end

app/views/tile_types/_form.html.erb
<%= form_for(@tile_type) do |f| %>
  <% if @tile_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tile_type.errors.count, "error") %> prohibited this tile_type from being saved:</h2>

      <ul>
      <% @tile_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :img %><br />
    <%= f.text_field :img %>
    X <%= f.text_field :img_x %>
    Y <%= f.text_field :img_y %>
  </div>
	<div class="field">
    <%= f.label :ownable %>
    <%= f.check_box :ownable %>
  </div>
	<div class="field">
    <%= f.label :is_store %>
    <%= f.check_box :is_store %>
  </div>
	<fieldset>
		<legend>Units Available</legend>
		<% @unit_types.each do |unit_type| %>
			<input type="checkbox" name="tile_type[unit_types_available][<%=unit_type.position%>]" <%= 'checked="checked"' if @tile_type.unit_types_available.include?(unit_type.position.to_s) %> />
			<%= unit_type.name %>
		<% end %>
	</fieldset>
  <div class="actions">
    <%= f.submit 'Save Tile Type', :class=>:button %>
  </div>
<% end %>

app/views/tile_types/edit.html.erb
<%= link_to 'Show', @tile_type, :class=>:button %>
<%= link_to 'Listing', tile_types_path, :class=>:button %>

<h1>Editing Tile Type</h1>

<%= render 'form' %>

app/views/tile_types/index.html.erb
<h1>Listing tile_types</h1>
<%= link_to 'New Tile type', new_tile_type_path, :class=>:button %>
<table class="model_index">
  <tr>
    <th>Name</th>
    <th>Img</th>
    <th></th>
  </tr>

<% @tile_types.each do |tile_type| %>
  <tr>
    <td><%= tile_type.name %></td>
    <td><%=display_tile_img(tile_type).html_safe%></td>
    <td><%= link_to 'Show', tile_type, :class=>:button %> <%= link_to 'Edit', edit_tile_type_path(tile_type), :class=>:button %> <%= link_to 'Destroy', tile_type, :confirm => 'Are you sure?', :method => :delete, :class=>:button %></td>
  </tr>
<% end %>
</table>

app/views/tile_types/new.html.erb
<h1>New tile_type</h1>

<%= render 'form' %>

<%= link_to 'Back', tile_types_path %>

app/views/tile_types/show.html.erb
<%= link_to 'Edit', edit_tile_type_path(@tile_type), :class=>:button %>
<%= link_to 'Listing', tile_types_path, :class=>:button %>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tile_type.name %>
</p>

<p>
  <b>Img:</b>
  <%= @tile_type.img %>
</p>

<p>
  <b>Position:</b>
  <%= @tile_type.position %>
</p>


<div class="field">
	<input type="checkbox" disabled="disabled" <%= 'checked="checked"' if @tile_type.is_store %> />
  is store
</div>
<fieldset>
	<legend>Units Available</legend>
	<% @unit_types.each do |unit_type| %>
		<input type="checkbox" disabled="disabled" <%= 'checked="checked"' if @tile_type.unit_types_available.include?(unit_type.position.to_s) %> />
		<%= unit_type.name %>
	<% end %>
</fieldset>