config/routes.rb
HexGame::Application.routes.draw do
  get "dev/qunit"

  get 'sessions/create'
  get 'sessions/new'

  post '/games/end_turn' => 'games#end_turn'
  get '/games/get_turn' => 'games#get_turn'
  get '/games/is_it_my_turn' => 'games#is_it_my_turn'
  post '/messages/:id/mark_read' => 'messages#mark_read'

  resources :games
  resources :maps
  resources :messages
  resources :players
  resources :tile_types
  resources :unit_types

  
  match "/auth/:provider/callback" => "sessions#create" 
  match "/auth/failure" => "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout 

  root :to => "games#index"

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :game_players, :dependent => :destroy
  has_many :games, :through => :game_players
  has_many :message_viewers, :dependent => :destroy
  has_many :messages, :through => :message_viewers
  has_many :turn_notifications
  validates :name, :presence=>true
  validates :uid, :presence=>true
  validates :provider, :presence=>true
  
  def self.create_with_omniauth(provider, user_id, token)
    faceboook_graph = Koala::Facebook::GraphAPI.new(token)
    profile = faceboook_graph.get_object("me")

    create! do |user|  
      user.provider = provider
      user.uid = user_id 
      user.token = token
      user.name = profile['name']
      user.email = profile['email']
      user.real_name = profile['name']
    end
    
  end
  
  # def update_from_facebook
  #   profile = faceboook_graph.get_object("me")
  # end
  
  def reset_facebook_token(token)
    @facebook_graph = nil
    @facebook_rest = nil
    self.token = token
    self.save!
  end

  def facebook_graph
    @faceboook_graph ||= Koala::Facebook::GraphAPI.new(self.token)
  end
  
  def facebook_rest
    @facebook_rest ||= Koala::Facebook::RestAPI.new(self.token)
  end
  
  def update_attributes(params)
    profile = self.facebook_graph.get_object("me")
    @name = profile['name']
    @email = profile['email']
    @real_name = profile['real_name']
    super(params)
  end
  
  def get_friends
    friend_list = facebook_rest.rest_call('friends_getAppUsers');
    Player.find(:all, :conditions => ["id <> #{self.id} AND uid IN (?)", friend_list])
  end
  
  def get_random_opponent(exclude_list=[])
    exclude_list << self.id
    players = Player.find(:all, :conditions => ["id NOT IN (?)", exclude_list])
    available_for_random = []
    players.each do |player|
      if player.available_for_random
        available_for_random << player
      end
    end

    available_for_random[rand(available_for_random.length)]
  end
end





# == Schema Information
#
# Table name: players
#
#  id                   :integer         not null, primary key
#  name                 :string(255)
#  created_at           :datetime
#  updated_at           :datetime
#  uid                  :string(255)
#  provider             :string(255)
#  admin                :boolean
#  email                :string(255)
#  notify_by_email      :boolean
#  real_name            :string(255)
#  available_for_random :boolean
#  token                :string(255)
#

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  skip_filter :need_to_update_profile
  skip_filter :check_admin
  before_filter :check_admin, :except=>[:show,:edit,:update]
  
  #
  # GET /players
  #
  def index
    @players = Player.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  #
  # GET /players/1
  #
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  #
  # GET /players/new
  #
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  #
  # GET /players/1/edit
  #
  def edit
    @player = Player.find(params[:id])
    unless current_player.admin || @player.id == current_player.id
     redirect_to(root_url)
    end
  end

  #
  # POST /players
  #
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to(players_url, :notice => 'Player was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  #
  # PUT /players/1
  #
  def update
    @player = Player.find(params[:id])
    unless current_player.admin || @player.id == current_player.id
     redirect_to(root_url)
     return
    end
    unless current_player.admin
      params[:player][:admin] = false
      
      #profile = faceboook_graph.get_object("me")
      #@player.real_name = profile['name']
      #@player.email = profile['email']
    end
    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to(root_url, :notice => 'Player was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  #
  # DELETE /players/1
  #
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to(players_url, :notice => 'Player was destroyed.') }
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
	<div class="field">
    <%= f.label :available_for_random, 'Available for Random Games' %>
    <%= f.check_box :available_for_random %>
	</div>
	<% if @current_player.admin %>
		<div class="field">
	    <%= f.label :admin %>
	    <%= f.check_box :admin %>
		</div>
	<% end %>
	<div class="field">
    <%= f.label :notify_by_email, 'Notify me when it is my turn' %>
    <%= f.check_box :notify_by_email %>
		<%= @player.email %>
	</div>
  <div class="actions">
    <%= f.submit 'Update', :class=>'button' %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

app/views/players/index.html.erb
<h1>Listing players</h1>
<%= link_to 'New Player', new_player_path, :class=>:button %>
<table class="model_index">
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= link_to 'Show', player, :class=>:button %> <%= link_to 'Edit', edit_player_path(player), :class=>:button %> <%= link_to 'Destroy', player, :confirm => 'Are you sure?', :method => :delete, :class=>:button %></td>
  </tr>
<% end %>
</table>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<h1><%= @player.name %></h1>

<p>
  <b>Games:</b>
	<ul class="game_list">
		<% @player.games.each do |game| %>
			<li><h2><%= game.name %></h2>
				<ul class="player_list">
					<% game.game_players.each do |game_player| %>
						<li>
							<%= image_tag 'misc/flag-'+	game_player.team+'-icon.png'%><%= link_to game_player.player.name, game_player.player %>
								<% if game_player.player == @current_player %>
									<script type="text/javascript">
										var current_player = '<%= game_player.team %>';
									</script>
									<span class="ui-silk ui-silk-user"></span>
								<% end %>
						</li>
					<% end %>
				</ul>
			</li>
		<% end %>
	</ul>
</p>