config/routes.rb
HexGame::Application.routes.draw do
  get "dev/qunit"

  get 'sessions/create'
  get 'sessions/new'

  post '/games/end_turn' => 'games#end_turn'
  get '/games/get_turn' => 'games#get_turn'
  get '/games/is_it_my_turn' => 'games#is_it_my_turn'
  post '/messages/:id/mark_read' => 'messages#mark_read'

  resources :games
  resources :maps
  resources :messages
  resources :players
  resources :tile_types
  resources :unit_types

  
  match "/auth/:provider/callback" => "sessions#create" 
  match "/auth/failure" => "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout 

  root :to => "games#index"

end

app/views/layouts/_preload.html.erb
<div id="loading" class="loading">
	<%= image_tag 'misc/loading-bar.gif' %>
</div>

<script type="text/javascript">
	// Hide the loading mask once the document is ready
	$(window).load(function () {
		$('#loading').delay(100).fadeOut(100);
		$('.preload').hide();
	});
</script>


<% image_tag '/images/misc/hex-highlight.png', :class => 'preload' %>
<% image_tag '/images/misc/mask.png', :class => 'preload' %> 
<% image_tag '/images/units.png', :class=> 'preload' %>
<% image_tag '/images/tiles.png', :class=> 'preload' %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Hexwar. The hex map, turn based, strategy game from your browser!</title>

	<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" />
	<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/themes/ui-darkness/jquery-ui.css" />

	<% if Rails.env == 'development' %>
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js"></script>
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.js"></script>
	<% else %>
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
	<% end %>
	<script src="http://connect.facebook.net/en_US/all.js"></script>
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tag %>
	
	<% if protect_against_forgery? %>
		<script type="text/javascript">
			var AUTH_TOKEN = <%=form_authenticity_token.inspect%>;
			// Always send the authenticity_token with ajax
			$(document).ajaxSend(function(event, request, settings) {
			    if ( settings.type == 'post' ) {
			        settings.data = (settings.data ? settings.data + "&" : "")
			            + "authenticity_token=" + encodeURIComponent( AUTH_TOKEN );
			    }
			});
		</script>
	<% end %>
	
	<!-- Tell IE6 to go away-->
	<!--[if lte IE 6]>
	<script src="/ie6/warning.js"></script>
	<script>$(function(){e("/ie6/")})</script>
	<![endif]-->
  
  <script type="text/javascript">
    $(function() {
    	$('.button').button();
		
		<% if notice %>
			Hexwar.UI.notify('<%= notice %>');
		<% end %>

		FB.init({
			appId  : '<%=HexGame::Application.config.hexwar['facebook']['app_id']%>',
			status : true, // check login status
			cookie : true, // enable cookies to allow the server to access the session
			xfbml  : true, // parse XFBML
			channelUrl : '<%=HexGame::Application.config.hexwar['host']%>/channel.html', // channel.html file
			oauth  : false // disable OAuth 2.0
		});

		FB.Canvas.setSize({ height: 1070 });
		
		Hexwar.config = {
			  unit_url: '/unit_types.json?cache=<%=resource_mtime('public/unit_types.json')%>'
			, tile_url: '/tile_types.json?cache=<%=resource_mtime('public/tile_types.json')%>'
		}
    });
  </script>

</head>
<body>
	<div id="fb-root"></div>
	<div id="facebook_canvas">

	<% if @current_player # ensure no crash at logout %>
		<script type="text/javascript">
		    $(function() {
				var notifier = new Hexwar.NotificationPoller(<%= @current_player.id %>);
				
				$('#btn_invite_friends').click(function(){
					FB.ui({method: 'apprequests'
						, message: 'Turn based strategy game for Facebook.'});
				});
		    });
	  	</script>

		<fieldset id="admin_nav">
			<legend><%= @current_player.name %></legend>
			<%= link_to 'My Games', games_path, :class=>'button' %>
			<%= link_to 'View Unit Types', unit_types_path, :class=>'button' %>
			<%= link_to 'My Profile', edit_player_path(@current_player), :class=>'button' %>
			<button id="btn_invite_friends" class="button">Invite Friends</button>

			<% if @current_player && @current_player.admin %>
				<br />
				<%= link_to 'Maps', maps_path, :class=>'button' %>
				<%= link_to 'Players', players_path, :class=>'button' %>
				<%= link_to 'TileTypes', tile_types_path, :class=>'button' %>
				<%= link_to 'Messages', messages_path, :class=>'button' %>
				<%= link_to 'Sign Out', signout_path, :class=>'button' %>
			<% end %>
			<br /> 
		</fieldset>

		<br />
	<% end %>

	<%= yield %>
	</div>
	<% if false && Rails.env != 'development' %>
		<div style="width:120px; height:600px; margin-top:30px; display:inline-block;vertical-align:top">
			<script type="text/javascript"><!--
				google_ad_client = "<%=HexGame::Application.config.hexwar['adsense']['google_ad_client']%>";
				google_ad_slot = "<%=HexGame::Application.config.hexwar['adsense']['google_ad_slot']%>";
				google_ad_width = 120;
				google_ad_height = 600;
			//--></script>
			<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
		</div>
	<% end %>
</body>
</html>